version: '3'
services:
    mongo:
        container_name: pbapi-mongo-dev-codeigniter-demo
        ports:
          - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=pass
            - MONGO_INITDB_DATABASE=core

    web:
        container_name: pbapi-web-dev-codeigniter-demo
        ports:
            - 80:80
        restart: always
        volumes:
            - ./main/php/codeigniter:/var/www/app
        environment:
            - MONGO_DB_URL=mongodb://root:pass@pbapi-mongo-dev-codeigniter-demo:27017
            - MONGO_HOST=pbapi-mongo-dev-codeigniter-demo
            - MONGO_PORT=27017
            - MONGO_USERNAME=root
            - MONGO_PASSWORD=pass
            - MONGO_DATABASE=pbapi
            - ENABLED_JSCONSOLE_DEBUG=true
            - DEVMODE=true
