ubuntu18_php7_mongo4:
    build: ./ubuntu18_php7_mongo4
    tty: true
    ports:
        - "8080:80"
        - "8443:443"
        - "27017:27017"
    volumes:
        - ./src:/src
        - ./log:/log
        - ./data:/data